language: ruby

env:
  - RUN_COVERAGE_REPORT=true

rvm:
  - 2.6.0
  - 2.7.0
  - 3.0.0

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - yes | gem update --system --force
  - gem install bundler
  - bundle install --gemfile=Gemfile --clean --path vendor/bundle

# uncomment this line if your project needs to run something other than `rake`:
script:
  - bundle exec rspec spec
  - bundle exec rubocop

gemfile:
  - gemfiles/dry_inflector_0_2_1.gemfile
  - gemfiles/i18n_1_8_11.gemfile
